from __future__ import annotations

import argparse
from pathlib import Path

from docx import Document


REPLACEMENTS = {
    "Synopsis. An open desktop workflow combines multiple open structure sources with global Match ranking and residual Gain scoring to support inspectable, user-guided identification of crystalline phases.":
    "Synopsis. Open desktop software supports automatic and semi-automatic interpretation of crystalline phases in powder mixtures using several structure sources, user CIF files, Match ranking and residual Gain scoring.",
    "Open crystal-structure repositories have made calculated powder diffraction libraries broadly accessible, but the interpretation of multiphase patterns still requires a transparent distinction between a candidate that resembles the complete pattern and one that explains intensity left after previously accepted phases. XRD Phase Finder is an open-source desktop application for preliminary phase identification from powder X-ray diffraction data. It integrates the Crystallography Open Database, Materials Project, AFLOW, OQMD and RRUFF resources, while also accepting user-supplied CIF files. Candidate patterns are calculated locally and inspected together with the experimental profile, phase markers and unexplained peaks. Initial candidates are ranked by a Match score that combines strong-peak position coverage, observed-peak coverage and relative-intensity agreement after a bounded global shift and scale search. Once phases have been selected, a Gain score ranks each remaining candidate by the weighted residual area that it can explain and penalizes calculated intensity unsupported by the residual. The graphical workflow keeps database filtering, preprocessing, candidate selection, profile comparison and project persistence under user control. The software is distributed under the MIT licence with standalone Windows and macOS packages. Match and Gain are interpretable ranking scores rather than phase probabilities or quantitative fractions; final structural and quantitative conclusions remain the domain of profile refinement and expert assessment.":
    "XRD Phase Finder is an open-source desktop application for interpreting which crystalline phases may be present in a powder mixture. It works in automatic and semi-automatic modes. Automatic search generates and ranks candidate phases, whereas the semi-automatic workflow allows the user to set elemental constraints, inspect the diffraction evidence and accept phases between residual-search iterations. The program searches user-accessible records from the Crystallography Open Database, Materials Project, AFLOW, OQMD and RRUFF, and it can evaluate individual CIF files without adding them to a database. Candidate diffraction patterns are calculated locally and displayed with the experimental profile, reflection markers, background components and unexplained lines. Match ranks the initial candidates by comparing calculated stick lines with the complete set of experimental line records. After one or more phases have been accepted, Gain re-ranks the remaining candidates according to evidence in the residual line set, so that entries duplicating already explained reflections are demoted. Smoothing, physical-background estimation and an optional broad amorphous contribution can be inspected and adjusted before subtraction. Projects retain the imported patterns, processing settings, accepted phases and view state. Standalone Windows and macOS packages are distributed under the MIT licence. Match and Gain are search-ranking scores, not phase probabilities or mass fractions. The result is an inspectable list of phases proposed for the mixture.",
    "Despite this progress, an open workflow may still require separate database searches, downloaded structures, pattern calculations and comparison tools. XRD Phase Finder was developed as a standalone, cross-platform workspace that combines multiple open structure sources, direct user-supplied CIF input, local indexing, interactive profile comparison and persistent projects. Its ranking separates two questions. Match estimates whether a candidate is globally compatible with the experimental peak set. Gain estimates the additional residual evidence contributed by a candidate after phases already accepted by the user have been fitted. The distinction is intended to make multiphase interpretation inspectable rather than to replace expert assessment or full-profile refinement.":
    "In practice, an open workflow still often involves separate database searches, downloaded structures, pattern calculations and comparison tools. XRD Phase Finder brings these steps into one cross-platform workspace. It searches several open structure sources, accepts user CIF files, builds local indexes, compares profiles interactively and saves the analysis as a project. The ranking answers two different questions. Match asks whether a candidate agrees with the experimental line set as a whole. Gain asks what additional residual evidence remains for that candidate after the user has accepted other phases. This separation keeps the reasoning in a multiphase search visible to the user.",
    "This article describes the software architecture, diffraction calculation, Match and Gain algorithms, and an evaluation framework for reproducible assessment. XRD Phase Finder is positioned as a hypothesis-generation and interpretation tool for the stage preceding Rietveld or Le Bail analysis.":
    "The following sections describe the software architecture, diffraction calculation, Match and Gain algorithms, and the validation used in this work. XRD Phase Finder is intended for automatic and semi-automatic interpretation of the crystalline phases present in powder mixtures.",
    "This formulation deliberately avoids assigning the next candidate by fitting a new broadened calculated profile to the residual. The ranking step instead asks whether the candidate's stick lines are supported by remaining experimental line integrals. The approach is lighter than Pawley, Le Bail or Rietveld refinement and is intended for hypothesis generation before full-profile analysis.":
    "The next candidate is not chosen by fitting another broadened calculated profile to the residual. Instead, the ranking asks whether its stick lines are supported by the remaining experimental line integrals. This keeps the residual search tied to discrete, visible line evidence.",
    "The relevant comparison is not whether a program can display COD structures. QUALX2.0 [4] and iQual [5] already provide efficient peak-based search against COD-derived collections. Full-profile search–match [6] and FullProfAPP [7] provide more rigorous profile-based testing and automated refinement, while XMatcher [8] is a close open and evidence-oriented comparison. Among commercial systems, Match! supports both peak-based and profile-fitting search–match and distributes a COD-derived reference database [9]; HighScore supports multiple reference databases and integrates phase identification with profile and Rietveld analysis [10]; JADE combines phase identification and whole-pattern fitting [11]; DIFFRAC.EVA 8 performs iterative Profile Fit Residual Search [12]; and STOE SEARCH/MATCH 2 supports COD together with background correction, peak processing and profile fitting [13].":
    "COD access and structure display are already available in established software. QUALX2.0 [4] and iQual [5] provide efficient peak-based searches of COD-derived collections. Full-profile search–match [6] and FullProfAPP [7] add profile-based testing and automated refinement, and XMatcher [8] offers an open comparison based on explicit peak evidence. Commercial packages cover a still broader range: Match! combines peak and profile-fitting searches with a COD-derived reference database [9]; HighScore links phase identification to profile and Rietveld analysis [10]; JADE combines phase identification with whole-pattern fitting [11]; DIFFRAC.EVA 8 includes iterative Profile Fit Residual Search [12]; and STOE SEARCH/MATCH 2 combines COD searching with background correction, peak processing and profile fitting [13].",
    "XRD Phase Finder should therefore be evaluated on the combination that defines its intended niche rather than on any one feature in isolation: open-source distribution, candidate generation from several open experimental and computational repositories [2,3,14–17], direct CIF inclusion, transparent peak-level and residual evidence, persistent interactive projects, and the ability of Gain to prioritize an additional candidate after accepted phases have been fitted. This claim must be tested directly against Match-only ranking and, where licences permit, against representative open and commercial search–match workflows [4–13].":
    "The useful comparison is therefore the complete workflow rather than a single feature. XRD Phase Finder combines open-source distribution, candidate generation from several experimental and computational repositories [2,3,14–17], direct CIF input, visible peak-level and residual evidence, persistent projects, and Gain ranking after accepted phases have been fitted. The evaluation below tests the added value of Gain against Match-only ranking. A broader comparison with open and commercial search–match workflows [4–13] will require matched database snapshots and, for licensed software, reproducible access to the same reference data.",
    "A fair benchmark should use the same chemical constraints and candidate availability for every method. Database coverage failures must be separated from ranking failures. Calculated structures should also be reported separately from experimental reference patterns because their relative intensities and relaxed lattice parameters have different evidential status. The present evaluation is therefore not framed as a tournament ranking of search-match programs. In realistic phase identification, the outcome can be dominated by the available and up-to-date database snapshot, redistribution permissions, preprocessing choices, chemical constraints, sample texture, peak overlap, background treatment and user expertise. The purpose of the benchmark in this work is narrower: to test whether the current XRD Phase Finder implementation behaves consistently in its intended role, namely producing inspectable phase hypotheses, avoiding unsupported residual additions and preserving graphical evidence for manual assessment.":
    "A comparison between programs is meaningful only when chemical constraints and candidate availability are held constant. A missing database entry is a coverage failure, not a ranking failure. Calculated structures must also be distinguished from experimental references because relaxed lattice parameters and calculated relative intensities carry different uncertainties. For these reasons, the present benchmark is not a league table of search–match programs. Its narrower aim is to determine whether this implementation produces stable shortlists, suppresses unsupported residual additions and leaves enough graphical evidence for the user to judge the result. Database snapshots, preprocessing, sample texture, peak overlap and background treatment are reported because each can change the outcome.",
    "The principal application window combines an experimental pattern, candidate table, element filters, selected phase list, structure card and database controls. The plot can show observed and processed signals, calculated profiles, reflection markers, fitted total intensity, background components, difference curves and unexplained-line markers. Candidate selection updates the preview without requiring a new database search. The examples used for the figures include a calcium aluminosilicate pattern in which several COD entries for Ca2Al2SiO7 compete, a natural gehlenite pattern where grossular is recovered as a residual phase, a broad low-intensity pattern requiring explicit amorphous-background handling, and a direct user-CIF stick preview.":
    "The main window keeps the experimental pattern, candidate table, element filters, selected phases, structure card and database controls in view. The plot can display raw and processed signals, calculated profiles, reflection markers, the fitted total, background components, a difference curve and unexplained-line markers. Selecting a candidate updates its preview without running the database search again. The examples in this paper include competing COD entries for Ca2Al2SiO7, a natural gehlenite sample in which grossular appears in the residual search, a broad low-intensity pattern that requires separate treatment of background and amorphous scattering, and a stick pattern loaded directly from a user CIF.",
    "In the first iteration no phase model exists, so candidates are ordered primarily by Match. This stage is designed to recover a dominant phase even when additional observed lines belong to impurities. In the Ca2Al2SiO7 example, several related COD entries have similar chemistry and space group information, but the line-integral Match score ranks COD#100048 Gehlenite at Match = 83% and Gain = 21%, and COD#4124699 Al2Ca2O7Si at Match = 81% and Gain = 22%. Both entries have similar I/Ic values of approximately 2.0, so source identity, reflection coverage and missing-line inspection remain necessary. Visual acceptance still requires agreement of several leading reflections and inspection of strong predicted lines that are absent from the experiment; a single coincident maximum is insufficient.":
    "Before any phase is accepted, the list is ordered mainly by Match. The purpose of this first pass is to recover the dominant phase without requiring every experimental line to belong to it. In the Ca2Al2SiO7 example, several COD entries have similar chemistry and space-group information. The line-integral score places COD#100048 Gehlenite at Match = 83% and Gain = 21%, followed closely by COD#4124699 Al2Ca2O7Si at Match = 81% and Gain = 22%. Their I/Ic values are both close to 2.0, so the ranking alone does not resolve the assignment. The user must still check the source record, coverage of the leading reflections and strong calculated lines that are absent from the experiment; one coincident maximum is not enough.",
    "After the dominant phase is accepted, candidate ordering changes from global similarity to incremental explanatory value. This distinction is most useful when several database entries represent the same structure type or when a minor phase shares its strongest reflection with the dominant phase. In the natural gehlenite example, selected gehlenite receives Quant. = 92.5% and I/Ic = 2.05, while selected grossular receives Quant. = 7.5% and I/Ic = 2.27. Once both phases are selected, further Ca-Al-Si candidates keep moderate Match values of roughly 40-47% but their residual Gain drops to about 0.1-1.3% because most leading lines are already covered. This behaviour is the central claim that should be quantified in the benchmark: Gain should improve minor-phase recovery without increasing unsupported false additions.":
    "Once the dominant phase is accepted, the ordering changes from overall resemblance to additional explanatory value. This is especially useful when several database entries describe the same structure type or when a minor phase shares its strongest reflection with the dominant phase. In the natural gehlenite example, the selected-phase table gives Quant. = 92.5% and I/Ic = 2.05 for gehlenite and Quant. = 7.5% and I/Ic = 2.27 for grossular. After both are selected, other Ca-Al-Si candidates retain Match values of about 40-47%, but their Gain falls to 0.1-1.3% because most of their leading lines are already covered. The benchmark tests the practical claim behind this behaviour: Gain should help recover an additional phase without encouraging unsupported additions.",
    "A 50-case internal benchmark was added to describe the current behaviour of the prototype rather than to claim a final, universal accuracy value. The set contains 30 experimental RRUFF mineral patterns and 20 synthetic profiles generated from measured RRUFF profiles. The synthetic profiles include one-, two- and three-phase cases, small 2theta shifts, line broadening, noise, background contribution and deliberate overlap. The candidate pool used for this run contained 162 patterns, including 140 RRUFF-derived references and 22 COD-derived calculated patterns. The COD target cache contained 48 locally indexed entries.":
    "We evaluated the current implementation on 50 cases. The set comprised 30 experimental RRUFF mineral patterns and 20 synthetic profiles derived from measured RRUFF data. The synthetic cases contained one, two or three phases and included small 2theta shifts, broadening, noise, background and deliberate peak overlap. The search pool contained 162 patterns: 140 RRUFF-derived references and 22 patterns calculated from COD structures. A further 48 COD entries were available in the local target cache. This is an internal prototype benchmark, not a universal accuracy estimate.",
    "For the 30 single-phase RRUFF patterns, the correct mineral name was ranked first in 30/30 cases and appeared in the top five in 30/30 cases. For the 20 synthetic profiles, at least one expected phase appeared first in 14/20 cases and appeared within the top five in 20/20 cases. This is interpreted as a current shortlist performance measure: the program is intended to guide inspection and candidate selection, not to replace expert interpretation or full-profile refinement.":
    "For all 30 single-phase RRUFF patterns, the correct mineral name ranked first and was therefore also present in the top five. Among the 20 synthetic profiles, at least one expected phase ranked first in 14 cases and appeared in the top five in all 20. These numbers describe candidate-list performance: the result still requires inspection of the diffraction evidence by the user.",
    "The Gain score is presently tuned conservatively. It requires residual line evidence above a robust three-sigma background estimate and several independent residual-line matches. This setting produced no false residual Gain above 5% in the 30 closed single-phase RRUFF tests. The trade-off is deliberate: a more permissive Gain mode may recover more overlapped or textured minor phases, but it would also be more likely to interpret preferred orientation, profile-width mismatch or background residuals as additional phases. In the current workflow, the difference curve and unexplained-line markers remain the expert-facing evidence for deciding whether a relaxed search is justified.":
    "Gain currently uses conservative thresholds: residual evidence must exceed a robust three-sigma background estimate and must include several independent line matches. Under these settings, none of the 30 closed single-phase RRUFF tests produced a false residual Gain above 5%. Relaxing the thresholds may recover more overlapped or textured minor phases, but it also increases the risk of treating preferred orientation, profile-width mismatch or background residuals as a new phase. The difference curve and unexplained-line markers are therefore retained as the evidence for deciding whether a broader search is justified.",
    "Background treatment is a dominant source of uncertainty for catalyst and mineral patterns. A flexible baseline can incorrectly follow the lower shoulders of crystalline peaks, whereas an overly rigid exponential background can leave holder scattering or diffuse intensity in the residual. XRD Phase Finder therefore separates an estimated physical background from an optional broad amorphous contribution and allows both to be visualized before subtraction. In the IM-2202 broad low-intensity example, the black curve represents the physical background, while the blue curve represents background + amorphous phase. The broad amorphous component is treated as a diffuse contribution rather than as a selected crystalline phase, preventing it from being misinterpreted as residual crystalline evidence.":
    "Background choice strongly affects catalyst and mineral patterns. A flexible baseline may climb into the shoulders of crystalline peaks, while a rigid exponential model may leave holder scattering or diffuse intensity in the residual. XRD Phase Finder therefore shows two estimates: the physical background and, when requested, the physical background plus a broad amorphous contribution. Both can be inspected before subtraction. In the IM-2202 example, the black curve is the physical background and the blue curve is the combined estimate. Their difference is treated as diffuse amorphous scattering, not as a selected crystalline phase.",
    "The present automatic mode selects parameters among explicit smoothing and baseline models. It should not be interpreted as a universal physical decomposition of instrumental background, amorphous material and nanocrystalline broadening. Validation must include patterns with low-angle holder contributions, diffuse halos, sharp and broad crystalline peaks, negative detector values and overlapping phases. Performance should be assessed by peak-area preservation and by stability of phase ranking, not by visual flatness alone.":
    "Automatic processing selects parameters for the explicit smoothing and baseline models described above. It cannot uniquely separate instrumental background, amorphous material and nanocrystalline broadening in every pattern. Validation must therefore include low-angle holder scattering, diffuse halos, narrow and broad crystalline peaks, negative detector values and overlapping phases. A useful setting should preserve peak area and phase ordering; a visually flat residual is not sufficient.",
    "Quantitative phase analysis requires appropriate profile and instrument models, scale factors, absorption treatment and, where relevant, an internal standard or reference-intensity-ratio strategy. XRD Phase Finder can supply a candidate phase set and an auditable interpretation state for such subsequent analysis, but the current version does not replace a validated Rietveld or Le Bail workflow.":
    "Quantitative phase analysis is outside the scope of the current version. Values shown in the selected-phase table summarize fitted profile contributions within the program and must not be reported as validated mass fractions.",
    "XRD Phase Finder provides a cross-platform, open-source environment for preliminary phase identification from powder diffraction data. Its contribution is not merely access to COD, which is already available through several mature programs. The program instead combines multiple open structure sources and direct CIF input with an inspectable iterative workflow. Match ranks initial global compatibility using experimental line records and calculated stick lines; Gain ranks additional residual-line evidence after accepted phases have marked their covered peaks. The interface preserves supporting and conflicting line evidence, processing choices and project state.":
    "XRD Phase Finder is a cross-platform, open-source workspace for interpreting which crystalline phases are present in a powder mixture. It supports both an automatic search and a semi-automatic workflow in which the user reviews and accepts phases between iterations. COD access by itself is not new. The contribution of the program is the combination of several open structure sources, direct CIF input and an iterative search whose evidence remains visible. Match compares calculated sticks with the complete set of experimental line records. After a phase is accepted, Gain ranks the evidence left in the residual line set. Supporting and conflicting lines, processing choices and the current phase model remain part of the saved project.",
    "The current 50-case benchmark provides an initial, reproducible description of prototype behaviour: dominant-phase retrieval is stable in the tested RRUFF set, residual Gain is conservative against false additions, and some weak or strongly overlapped impurities remain dependent on difference-curve inspection. Further work should expand the public benchmark, report corundum-normalized impurity detectability, and compare conservative and relaxed Gain settings with independent-user evaluation.":
    "In the 50 cases tested here, dominant-phase retrieval was stable for the RRUFF single-phase set and the conservative Gain settings avoided false additions above 5%. Weak and strongly overlapped impurities were less consistent and still required inspection of the difference curve. The next validation step is a larger public benchmark with corundum-normalized impurity levels, conservative and relaxed Gain settings, and evaluation by users who were not involved in development.",
}


def replace_paragraph_text(paragraph, new_text: str) -> None:
    paragraph.text = new_text


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    document = Document(args.source)
    replaced = 0
    for paragraph in document.paragraphs:
        replacement = REPLACEMENTS.get(paragraph.text)
        if replacement is None:
            continue
        replace_paragraph_text(paragraph, replacement)
        replaced += 1

    missing = len(REPLACEMENTS) - replaced
    if missing:
        raise RuntimeError(f"Only {replaced}/{len(REPLACEMENTS)} target paragraphs were replaced")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    document.save(args.output)
    print(f"Revised {replaced} paragraphs: {args.output}")


if __name__ == "__main__":
    main()
