from __future__ import annotations


PHASE_FINDER_HELP_TITLE = "XRD Phase Finder Help"

PHASE_FINDER_HELP_TEXT = (
    "Quick help\n\n"
    "Project tree\n"
    "- Select an XRD row to make it active for search, preview and calculation.\n"
    "- Checkboxes control which XRD patterns or CIF phases are visible.\n"
    "- Double click an XRD row to show only that pattern.\n"
    "- Right click the project to add a series; right click an XRD/CIF row to move it between series.\n"
    "- Select a series before importing files to place the new XRD/CIF items inside it.\n"
    "- Drag a folder into the window to create series automatically; supported files in each direct subfolder are grouped together.\n"
    "- Use Order arrows to change plot and legend order.\n\n"
    "Element table\n"
    "- Left click: required element, shown in blue.\n"
    "- Right click: optional element, shown in green.\n"
    "- Click again to remove that element from the gate.\n\n"
    "Candidate list\n"
    "- Single click: preview candidate peaks and show the card.\n"
    "- Double click: add the candidate to Selected candidates.\n"
    "- Right click: add, calculate overlay, or export candidate CIF.\n\n"
    "Selected candidates\n"
    "- Single click: show that selected phase on the plot and card.\n"
    "- Double click the Phase cell to rename the phase in tables and figures.\n"
    "- Right click: rename, change color, export CIF, remove phase, or clear the list.\n\n"
    "Plot\n"
    "- Mouse wheel or drag: zoom/pan.\n"
    "- Reset view restores the full pattern.\n"
    "- Right click the plot to export an image or show the full pattern.\n\n"
    "Databases\n"
    "- Databases are enabled with checkboxes.\n"
    "- Large COD/RRUFF databases are downloaded and indexed only when you choose it."
)
